version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 8nP7s0a    # Can not be changed again later on
    volumes:
      - database:/data/db
    networks:
      - senty

  dbadmin:
    image: mongo-express
    container_name: dbadmin
    restart: unless-stopped
    ports:
      - "8089:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin    # Access to web interface: username
      ME_CONFIG_BASICAUTH_PASSWORD: admin   # Access to web interface: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 8nP7s0a  # must correspond to the db
      ME_CONFIG_MONGODB_PORT: 27017 # Default 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - senty
networks:
  senty:
    driver: bridge

volumes:
  database: